[package]
name = "cv-input"
version.workspace = true
edition.workspace = true

[dependencies]
cv-shared = { path = "../cv-shared" }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
libc = "0.2.186"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
] }
