//! Protobuf-generated module wrapper.
//!
//! This module re-exports the types generated by `prost-build` from the
//! `.proto` definitions located in `crates/cv-shared/proto/`.
//!
//! The code is generated at compile time by the `build.rs` script and
//! placed in `OUT_DIR`. We include the generated files here to make them
//! available under the `cv_shared::proto` namespace.
//!
//! # Generated Modules
//!
//! - `rendezvous` — Rendezvous/signaling messages (peer registration, hole punching, relay).
//! - `message` — Data channel messages (input events, chat, video frames, system messages).

/// Include the generated rendezvous module.
pub mod rendezvous {
    include!(concat!(env!("OUT_DIR"), "/clawviewer.rendezvous.rs"));
}

/// Include the generated message module.
pub mod message {
    include!(concat!(env!("OUT_DIR"), "/clawviewer.message.rs"));
}
