//! Shared types used across all ClawViewer crates.
//!
//! This module defines the core data types for sessions, peers, input events,
//! video configuration, and platform abstraction. All types are designed to be
//! thread-safe (`Send + Sync`) and suitable for async contexts.

use serde::{Deserialize, Serialize};
use zeroize::{Zeroize, ZeroizeOnDrop};

// ---------------------------------------------------------------------------
// Identifier types
// ---------------------------------------------------------------------------

/// Unique identifier for a ClawViewer session.
///
/// A session groups a set of peers together for remote desktop sharing.
/// The identifier is typically a human-readable string.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(pub String);

impl SessionId {
    /// Create a new [`SessionId`] from any string-like value.
    pub fn new<S: Into<String>>(id: S) -> Self {
        SessionId(id.into())
    }
}

impl Default for SessionId {
    fn default() -> Self {
        SessionId(String::new())
    }
}

/// Unique identifier for a peer in the ClawViewer network.
///
/// Each installation of ClawViewer has a stable peer ID derived from its
/// Ed25519 public key.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PeerId(pub String);

impl PeerId {
    /// Create a new [`PeerId`] from any string-like value.
    pub fn new<S: Into<String>>(id: S) -> Self {
        PeerId(id.into())
    }
}

impl Default for PeerId {
    fn default() -> Self {
        PeerId(String::new())
    }
}

/// Session password used for peer authentication.
///
/// The password is a short human-friendly word (6 alphanumeric characters)
/// that must be shared out-of-band to join a session.
///
/// # Security
///
/// This struct derives [`ZeroizeOnDrop`] to ensure the password is wiped
/// from memory when the value is dropped, preventing leakage via memory
/// inspection.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, Zeroize, ZeroizeOnDrop)]
pub struct Password(pub String);

impl Password {
    /// Create a new [`Password`] from any string-like value.
    ///
    /// # Security
    ///
    /// The input string will be zeroized when this [`Password`] is dropped.
    pub fn new<S: Into<String>>(pwd: S) -> Self {
        Password(pwd.into())
    }
}

impl Default for Password {
    fn default() -> Self {
        Password(String::new())
    }
}

// ---------------------------------------------------------------------------
// Platform & Video
// ---------------------------------------------------------------------------

/// Target platform for the ClawViewer application.
///
/// Used to gate platform-specific functionality (e.g. DXGI capture on Windows).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Platform {
    /// Microsoft Windows (10/11)
    Windows,
    /// Linux distributions
    Linux,
    /// Apple macOS
    MacOS,
}

/// Supported video codecs for screen capture streaming.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum VideoCodec {
    /// H.264 / AVC — widely supported, good balance of quality and compression.
    H264,
    /// VP9 — royalty-free, excellent compression, higher CPU usage.
    VP9,
    /// AV1 — next-generation royalty-free codec, best compression.
    AV1,
}

// ---------------------------------------------------------------------------
// Input Events
// ---------------------------------------------------------------------------

/// The source of an input event.
///
/// Distinguishes between human input, AI-generated actions, and system events.
/// This is critical for the priority queue and emergency-stop logic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventSource {
    /// Input generated by a human operator (highest priority after emergency).
    Human,
    /// Input generated by the AI agent.
    AI,
    /// System-generated events (heartbeat, status updates).
    System,
}

/// Mouse button identifiers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MouseButton {
    /// Left mouse button.
    Left,
    /// Right mouse button.
    Right,
    /// Middle (scroll wheel) mouse button.
    Middle,
}

/// Specific input event types.
///
/// Each variant carries the data needed to replay the event on the remote
/// machine via the platform's input injection API (`SendInput` on Windows).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventType {
    /// Move the mouse cursor to absolute screen coordinates.
    MouseMove {
        /// Absolute X coordinate in screen pixels.
        x: i32,
        /// Absolute Y coordinate in screen pixels.
        y: i32,
    },
    /// Press or release a mouse button.
    MouseClick {
        /// Which button was actuated.
        button: MouseButton,
        /// `true` if the button was pressed, `false` if released.
        down: bool,
    },
    /// Scroll the mouse wheel vertically.
    MouseScroll {
        /// Positive values scroll up, negative values scroll down.
        delta: i32,
    },
    /// Press or release a keyboard key.
    KeyPress {
        /// Virtual-key code (Windows `wVk` format).
        keycode: u16,
        /// `true` if the key was pressed, `false` if released.
        down: bool,
    },
    /// Type a sequence of Unicode characters.
    KeyType {
        /// The text string to type character-by-character.
        text: String,
    },
}

/// Priority levels for input events.
///
/// # Ordering
///
/// Priorities are ordered from highest to lowest urgency:
/// - [`Priority::P0_Emergency`] — Emergency stop (always processed first).
/// - [`Priority::P1_Human`] — Human input (always takes precedence over AI).
/// - [`Priority::P2_AI_Confirmed`] — AI actions that require human confirmation.
/// - [`Priority::P3_AI_Autonomous`] — Fully autonomous AI actions (lowest).
///
/// This ordering is implemented via [`Ord`] so the type can be used directly
/// in a [`std::collections::BinaryHeap`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Priority {
    /// Emergency stop — immediately halts all AI activity.
    P0_Emergency,
    /// Human input — always takes precedence over AI actions.
    P1_Human,
    /// AI action that has been explicitly confirmed by a human.
    P2_AI_Confirmed,
    /// Fully autonomous AI action (lowest priority).
    P3_AI_Autonomous,
}

impl Priority {
    /// Returns the numeric priority value.
    ///
    /// Lower numbers = higher priority (0 is highest, 3 is lowest).
    pub fn as_u8(&self) -> u8 {
        match self {
            Priority::P0_Emergency => 0,
            Priority::P1_Human => 1,
            Priority::P2_AI_Confirmed => 2,
            Priority::P3_AI_Autonomous => 3,
        }
    }
}

impl Ord for Priority {
    /// Reversed ordering so that P0 (highest) sorts first.
    ///
    /// `BinaryHeap` is a max-heap, so we compare "other vs self" so that
    /// lower numeric values (higher priority) come out first.
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        other.as_u8().cmp(&self.as_u8())
    }
}

impl PartialOrd for Priority {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

// ---------------------------------------------------------------------------
// InputEvent
// ---------------------------------------------------------------------------

/// A complete input event as transmitted over the WebRTC DataChannel.
///
/// This struct is serialized to JSON (or protobuf) and sent to the remote
/// peer, where it is deserialized and replayed via the input injection API.
///
/// # Fields
///
/// - `source`: Who/what generated the event.
/// - `event_type`: What kind of input action this is.
/// - `priority`: Urgency level for the priority queue.
/// - `payload`: Additional event data (JSON-serialized).
/// - `timestamp`: Unix timestamp in milliseconds (sender clock).
/// - `sequence`: Monotonically increasing sequence number for ordering.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct InputEvent {
    /// The source that generated this event.
    pub source: EventSource,
    /// The type of input action.
    pub event_type: EventType,
    /// Priority level for queue ordering.
    pub priority: Priority,
    /// JSON-serialized payload (for extensibility).
    pub payload: EventPayload,
    /// Unix timestamp in milliseconds.
    pub timestamp: u64,
    /// Monotonically increasing sequence number.
    pub sequence: u64,
}

/// Additional payload data for an input event.
///
/// This is a thin newtype around `String` that carries JSON data.
/// Using a dedicated type allows us to add validation or structured
/// accessors in the future without breaking the API.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EventPayload(pub String);

impl EventPayload {
    /// Create an empty payload.
    pub fn empty() -> Self {
        EventPayload(String::new())
    }

    /// Create a payload from a JSON-serializable value.
    ///
    /// # Errors
    ///
    /// Returns an error if serialization fails.
    pub fn from_json<T: Serialize>(value: &T) -> Result<Self, serde_json::Error> {
        Ok(EventPayload(serde_json::to_string(value)?))
    }
}

impl Default for EventPayload {
    fn default() -> Self {
        Self::empty()
    }
}

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

/// A rectangle defined by left, top, width, height.
///
/// Used for dirty region tracking in screen capture.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Rect {
    /// Left coordinate (inclusive).
    pub left: u32,
    /// Top coordinate (inclusive).
    pub top: u32,
    /// Width in pixels.
    pub width: u32,
    /// Height in pixels.
    pub height: u32,
}

impl Rect {
    /// Create a new rectangle.
    pub fn new(left: u32, top: u32, width: u32, height: u32) -> Self {
        Self { left, top, width, height }
    }

    /// Right coordinate (exclusive).
    pub fn right(&self) -> u32 {
        self.left + self.width
    }

    /// Bottom coordinate (exclusive).
    pub fn bottom(&self) -> u32 {
        self.top + self.height
    }
}

// ---------------------------------------------------------------------------
// Send + Sync assertions
// ---------------------------------------------------------------------------

/// Compile-time assertions that all public types are thread-safe.
#[allow(dead_code)]
fn _assert_send_sync() {
    fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<SessionId>();
    assert_send_sync::<PeerId>();
    assert_send_sync::<Password>();
    assert_send_sync::<Platform>();
    assert_send_sync::<VideoCodec>();
    assert_send_sync::<EventSource>();
    assert_send_sync::<EventType>();
    assert_send_sync::<MouseButton>();
    assert_send_sync::<Priority>();
    assert_send_sync::<InputEvent>();
    assert_send_sync::<EventPayload>();
    assert_send_sync::<Rect>();
}
